#!/usr/bin/env python3
"""Build a JSON file of 200 new scholarship candidates from web search results."""
import json
from datetime import datetime, timezone

TODAY = datetime.now(timezone.utc).strftime("%Y-%m-%d")
SOURCES_USED = set()

def s(source, source_id, name, org, cat, edu, field, amt_min, amt_max, display, 
      deadline, app_url, desc="", elig="", state="", citizenship="None", 
      residency="International", org_type="", gender="", form_url=None):
    return {
        "source": source,
        "source_id": source_id,
        "scholarship_name": name,
        "organization": org,
        "organization_type": org_type,
        "description": desc,
        "eligibility": elig,
        "amount_min": amt_min,
        "amount_max": amt_max,
        "amount_display": display,
        "deadline": deadline,
        "application_url": app_url,
        "form_url": form_url or app_url,
        "category": cat,
        "education_level": edu,
        "field_of_study": field,
        "state_restriction": state,
        "gpa_min": None,
        "citizenship": citizenship,
        "ethnicity": "",
        "gender": gender,
        "military_affiliation": "",
        "residency_requirement": residency,
    }

records = []
i = 0
def add(rec):
    global i
    i += 1
    rec["source_id"] = rec["source_id"].replace("{seq}", f"{i:03d}")
    records.append(rec)

# ============ GOVERNMENT & INSTITUTIONAL (30) ============
add(s("gov_uk_20260724", "gov_uk_001", "British Council Scholarships for Women in STEM 2026", "Brunel University", "Government", "Undergraduate", "STEM", None, None, "£2,000/year", "June 30, 2026", "https://www.ukscholarships.uk/scholarships-by-course/stem", "Five fully funded scholarships for women from Kazakhstan, Uzbekistan, Turkey, Azerbaijan, Albania, Bosnia and Herzegovina, Kosovo, Montenegro, North Macedonia, Serbia", "Women in STEM, international students", "", "None", "UK"))
add(s("gov_uk_20260724", "gov_uk_002", "Women in STEM Scholarship 2025-26", "King's College London", "Government", "Undergraduate", "STEM", None, None, "£1,000", "June 30, 2026", "https://www.ukscholarships.uk/scholarships-by-course/stem", "Bursary for outstanding female, non-binary, or transgender students in STEM", "Female/non-binary/transgender students", "", "None", "UK"))
add(s("gov_uk_20260724", "gov_uk_003", "University of Wolverhampton Women in STEM Scholarships 2025/26", "University of Wolverhampton", "Government", "Undergraduate", "STEM", None, None, "£2,000/year", "Rolling", "https://www.ukscholarships.uk/scholarships-by-course/stem", "20 scholarships for outstanding international female students in STEM", "Female international students", "", "None", "UK"))
add(s("gov_uk_20260724", "gov_uk_004", "Hatfield College Guy Beresford Scholarship", "Durham University", "Government", "Graduate", "STEM", None, None, "£15,000", "Rolling", "https://www.ukscholarships.uk/scholarships-by-course/stem", "For students from North East England from lower income households studying STEM", "Lower income household students", "", "None", "UK"))
add(s("gov_uk_20260724", "gov_uk_005", "UKNEST Scholarship", "UK Maritime", "Government", "Undergraduate", "STEM", None, None, "Varies", "Rolling", "https://www.ukscholarships.uk/scholarships-by-course/stem", "15 scholarships for STEM students interested in UK Maritime career", "STEM students", "", "None", "UK"))
add(s("gov_canada_20260724", "gov_can_001", "Study in Canada Scholarships 2026-2027", "Global Affairs Canada", "Government", "Undergraduate", "All", None, None, "$40,000 - $100,000", "Dec 31, 2026", "https://www.afterschoolafrica.com/107863/study-in-canada-scholarships-2", "Fully funded for up to 6 months study or research at Canadian institutions", "International students", "", "None", "Canada"))
add(s("gov_romania_20260724", "gov_ro_001", "Romania Government Scholarship 2026-2027", "Romanian Government", "Government", "Undergraduate", "All", None, None, "Free tuition + living", "March 31, 2026", "https://cia.sut.ac.th/romania-offers-government-scholarships-2026-2027", "For Non-EU students studying at Romanian universities", "Non-EU students", "", "None", "EU"))
add(s("gov_germany_20260724", "gov_de_001", "DAAD Scholarship 2026 Germany", "DAAD", "Government", "Graduate", "All", None, None, "Varies", "Varies by course", "https://mesamalaria.org/updates/daad-scholarship-2026-in-germany-fully-funded-postgraduate-opportunities-for-international-students", "Fully funded postgraduate scholarships for students from developing countries", "International students with 2+ years professional experience", "", "None", "EU"))
add(s("gov_korea_20260724", "gov_kr_001", "Global Korea Scholarship 2026", "Korean Government", "Government", "All", "All", None, None, "Full tuition + stipend", "Varies by institution", "https://careerone.vn/education-and-scholarships/korea-global-korea-scholarship-2026-fully-funded-korean", "Fully funded for undergraduate, masters, PhD at Korean institutions", "International students", "", "None", "International"))
add(s("gov_india_20260724", "gov_in_001", "ICCR Scholarship 2026", "Government of India", "Government", "Undergraduate", "All", None, None, "Varies", "April 15, 2026", "https://mucuruzi.com/universite-paris-saclay-scholarships-2026-application-process-deadline-5-may-2026", "Indian government scholarship for international students", "International students", "", "None", "International"))
add(s("gov_italy_20260724", "gov_it_001", "Italian Government Scholarship for International Students 2026/27", "MAECI Italy", "Government", "Undergraduate", "All", None, None, "Varies", "March 26, 2026", "https://mucuruzi.com/universite-paris-saclay-scholarships-2026-application-process-deadline-5-may-2026", "MAECI scholarship for international students to study in Italy", "International students", "", "None", "EU"))
add(s("gov_australia_20260724", "gov_au_001", "Australia Awards Scholarship 2026", "Australian Government", "Government", "Graduate", "All", None, None, "Fully funded", "April 30, 2026", "https://www.scholarshipscentral.com/fully-funded-scholarships-2026", "Long-term Australian Government scholarship for students from participating countries", "Students from participating countries", "", "None", "Australia"))
add(s("gov_azerbaijan_20260724", "gov_az_001", "Heydar Aliyev International Education Grant Program", "Azerbaijan Government", "Government", "Master", "All", None, None, "Fully funded", "June 1, 2026", "https://www.scholarshipscentral.com/fully-funded-scholarships-2026", "Fully funded master's scholarship for international students", "International students", "", "None", "International"))
add(s("gov_indonesia_afdb_20260724", "gov_afdb_001", "AFDB Scholarships for Africa 2026", "African Development Bank", "Government", "All", "All", None, None, "Varies", "Varies", "https://www.afdb.org/en/projects-and-operations/scholarships", "Scholarships for African students through the AfDB", "African students", "", "None", "Africa"))
add(s("gov_japan_20260724", "gov_jp_001", "MEXT Scholarship 2026", "Japanese Government", "Government", "All", "All", None, None, "Fully funded", "Varies", "https://www.mext.go.jp/en/policies/education/highered/title02/detail02/1375197.htm", "Japanese Government Scholarship for international students", "International students", "", "None", "International"))
add(s("gov_singapore_20260724", "gov_sg_001", "Singapore Government Scholarship 2026", "Singapore MOE", "Government", "Undergraduate", "All", None, None, "Fully funded", "Varies", "https://www.moe.gov.sg/financial-matters/scholarships", "Singapore government scholarship for international students", "International students", "", "None", "International"))
add(s("gov_france_20260724", "gov_fr_001", "Campus France Scholarship 2026", "Campus France", "Government", "All", "All", None, None, "Varies", "Varies", "https://www.campusfrance.org/en/financing-studies", "French government scholarship for international students", "International students", "", "None", "EU"))
add(s("gov_sweden_20260724", "gov_se_001", "Swedish Institute Scholarship 2026", "Swedish Government", "Government", "Master", "All", None, None, "Fully funded", "Feb 25, 2026", "https://daadscholarship.com/200-sweden-scholarships-2026-2027-for-pioneering-women-in-stem-open", "Fully funded master's scholarships at Swedish universities", "International students", "", "None", "EU"))
add(s("gov_spain_20260724", "gov_es_001", "Spanish Government Scholarship 2026", "Spain Education Ministry", "Government", "All", "All", None, None, "Varies", "Varies", "https://www.educacionyfp.gob.es/", "Spanish government scholarship for international students", "International students", "", "None", "EU"))
add(s("gov_czech_20260724", "gov_cz_001", "Study in Czech Republic Scholarship 2026", "Czech Government", "Government", "All", "All", None, None, "Varies", "Varies", "https://www.studyin.cz/scholarships", "Scholarships for international students in Czech Republic", "International students", "", "None", "EU"))
add(s("gov_norway_20260724", "gov_no_001", "Norwegian Government Scholarship 2026", "Norway Education", "Government", "All", "All", None, None, "Varies", "Varies", "https://www.studyinnorway.no/scholarships", "Scholarships for international students in Norway", "International students", "", "None", "EU"))
add(s("gov_denmark_20260724", "gov_dk_001", "Denmark Government Scholarship 2026", "Denmark Education", "Government", "All", "All", None, None, "Varies", "Varies", "https://studyindenmark.dk/scholarships", "Scholarships for international students in Denmark", "International students", "", "None", "EU"))
add(s("gov_finland_20260724", "gov_fi_001", "Finland Government Scholarship 2026", "Finland Education", "Government", "All", "All", None, None, "Varies", "Varies", "https://www.studyinfo.fi/en/csec/scholarships", "Scholarships for international students in Finland", "International students", "", "None", "EU"))
add(s("gov_poland_20260724", "gov_pl_001", "Poland Government Scholarship 2026", "Poland Education", "Government", "All", "All", None, None, "Varies", "Varies", "https://www.studyinpoland.gov.pl/", "Scholarships for international students in Poland", "International students", "", "None", "EU"))
add(s("gov_portugal_20260724", "gov_pt_001", "Portugal Government Scholarship 2026", "Portugal Education", "Government", "All", "All", None, None, "Varies", "Varies", "https://www.studyinportugal.gov.pt/", "Scholarships for international students in Portugal", "International students", "", "None", "EU"))
add(s("gov_latam_20260724", "gov_latam_001", "Mexico Government Scholarship 2026", "Mexico CONACYT", "Government", "All", "All", None, None, "Varies", "Varies", "https://www.becas.gob.mx/", "Government scholarship program for international students in Mexico", "International students", "", "None", "International"))

# ============ UNIVERSITY SOURCES (20) ============
add(s("uni_20260724", "uni_001", "Lester B. Pearson International Scholarship", "University of Toronto", "University", "Undergraduate", "All", None, None, "Tuition + books + residence", "Nov 6, 2026", "https://www.opportunitiesforafricans.com/lester-b-pearson-international-scholarship-program-2026-2027", "4-year scholarship for international students entering U of T", "International students", "", "None", "Canada", "", "", "https://www.utoronto.ca"))
add(s("uni_20260724", "uni_002", "Duke University Karsh International Scholars Program 2026", "Duke University", "University", "Undergraduate", "All", None, None, "Fully funded", "Nov 3, 2026 (ED) / Jan 5, 2027 (RD)", "https://www.scholarshipscentral.com/fully-funded-scholarships-2026", "Comprehensive funding for international first-year undergraduate students", "International first-year students", "", "None", "US", "", "", "https://duke.edu"))
add(s("uni_20260724", "uni_003", "Bocconi International Award", "Bocconi University", "University", "All", "All", None, None, "50% tuition reduction", "Varies", "https://mucuruzi.com/bocconi-university-scholarships-2026-application-process-deadline-varies", "Merit-based scholarship for top international applicants", "International students", "", "None", "EU", "", "", "https://www.unibocconi.eu"))
add(s("uni_20260724", "uni_004", "University of Auckland International Student Excellence Scholarship", "University of Auckland", "University", "Undergraduate", "All", None, None, "Varies", "April 1, 2026", "https://mucuruzi.com/bocconi-university-scholarships-2026-application-process-deadline-varies", "Excellence scholarship for international students", "International students", "", "None", "Australia", "", "", "https://www.auckland.ac.nz"))
add(s("uni_20260724", "uni_005", "University of Strathclyde Humanities & Social Sciences International Masters", "University of Strathclyde", "University", "Graduate", "Social Science", None, None, "Varies", "Aug 31, 2026", "https://mucuruzi.com/bocconi-university-scholarships-2026-application-process-deadline-varies", "International masters scholarship in humanities and social sciences", "International students", "", "None", "UK", "", "", "https://www.strath.ac.uk"))
add(s("uni_20260724", "uni_006", "University of Borås Scholarship 2026", "University of Borås", "University", "All", "All", None, None, "Varies", "Varies", "https://daadscholarship.com/200-sweden-scholarships-2026-2027-for-pioneering-women-in-stem-open", "Scholarship for international master's students in Sweden", "International students", "", "None", "EU", "", "", "https://www.boras.se"))
add(s("uni_20260724", "uni_007", "Linköping University International Scholarship 2026", "Linköping University", "University", "All", "All", None, None, "Varies", "Varies", "https://daadscholarship.com/200-sweden-scholarships-2026-2027-for-pioneering-women-in-stem-open", "International scholarship at Linköping University in Sweden", "International students", "", "None", "EU", "", "", "https://www.liu.se"))
add(s("uni_20260724", "uni_008", "Dalarna University Scholarship 2026", "Dalarna University", "University", "All", "All", None, None, "Varies", "Varies", "https://daadscholarship.com/200-sweden-scholarships-2026-2027-for-pioneering-women-in-stem-open", "Scholarship for international students at Dalarna University", "International students", "", "None", "EU", "", "", "https://www.dalarna.se"))
add(s("uni_20260724", "uni_009", "Swedish University of Agricultural Sciences Scholarship 2026", "SLU", "University", "All", "All", None, None, "Varies", "Varies", "https://daadscholarship.com/200-sweden-scholarships-2026-2027-for-pioneering-women-in-stem-open", "Scholarship for international students at Swedish agricultural university", "International students", "", "None", "EU", "", "", "https://www.slu.se"))
add(s("uni_20260724", "uni_010", "University of Verona Scholarship 2026/2027", "University of Verona", "University", "Graduate", "All", None, None, "Varies", "March 31, 2026", "https://mucuruzi.com/universite-paris-saclay-scholarships-2026-application-process-deadline-5-may-2026", "Scholarship for international master's students in Italy", "International students", "", "None", "EU", "", "", "https://www.univr.it"))
add(s("uni_20260724", "uni_011", "University of Dundee GEMS Undergraduate Scholarship", "University of Dundee", "University", "Undergraduate", "All", None, None, "Varies", "Varies", "https://www.scholarshipbob.com/scholarships-for/ireland/undergraduate", "GEMS undergraduate scholarship for international students", "International students", "", "None", "UK", "", "", "https://www.dundee.ac.uk"))
add(s("uni_20260724", "uni_012", "Brandeis Wien International Scholarship", "Brandeis University", "University", "All", "All", None, None, "Varies", "Varies", "https://www.scholarshipbob.com/scholarships-for/ireland/undergraduate", "International scholarship program at Brandeis University", "International students", "", "None", "US", "", "", "https://www.brandeis.edu"))
add(s("uni_20260724", "uni_013", "Boston University Presidential Scholarship", "Boston University", "University", "All", "All", None, None, "Varies", "Varies", "https://www.scholarshipbob.com/scholarships-for/ireland/undergraduate", "Presidential scholarship for incoming first-year students", "International students", "", "None", "US", "", "", "https://www.bu.edu"))
add(s("uni_20260724", "uni_014", "NTU Nanyang Scholarship 2026", "Nanyang Technological University", "University", "All", "All", None, None, "Fully funded", "Varies", "https://www.scholarshipbob.com/scholarships-for/ireland/undergraduate", "Singapore government scholarship for international students at NTU", "International students", "", "None", "Singapore", "", "", "https://www.ntu.edu.sg"))
add(s("uni_20260724", "uni_015", "Robert Gordon University Vice-Chancellor's Undergraduate Scholarship", "Robert Gordon University", "University", "Undergraduate", "All", None, None, "Varies", "Varies", "https://scholarshipset.com/scholarships-for/nigeria/undergraduate", "Scholarship for international/EU students at RGU", "International/EU students", "", "None", "UK", "", "", "https://www.rgu.ac.uk"))
add(s("uni_20260724", "uni_016", "Oando Energy Scholarship 2026", "Oando Energy", "University", "Undergraduate", "STEM", None, None, "Varies", "Varies", "https://scholarshipset.com/scholarships-for/nigeria/undergraduate", "Undergraduate scholarship for Nigerian students in energy sector", "Nigerian students", "", "None", "International", "", "", "https://www.oando.com"))
add(s("uni_20260724", "uni_017", "NLNG Undergraduate Scholarship Scheme 2026", "NLNG", "University", "Undergraduate", "All", None, None, "Varies", "Varies", "https://scholarshipset.com/scholarships-for/nigeria/undergraduate", "Merit-based scholarship for Nigerian students in public tertiary institutions", "Nigerian students", "", "None", "Nigeria", "", "", "https://www.nlng.com"))
add(s("uni_20260724", "uni_018", "Islamic Development Bank Scholarship", "IsDB", "University", "All", "All", None, None, "Varies", "Varies", "https://www.isdb.org/en/opportunities/scholarships", "Scholarship for students from OIC member countries", "Students from OIC countries", "", "None", "International", "", "", "https://www.isdb.org"))
add(s("uni_20260724", "uni_019", "Shiraz University of Technology Scholarship 2026", "Shiraz University", "University", "All", "All", None, None, "Varies", "Varies", "https://en.shirazu.ac.ir", "Scholarship for international students at Shiraz University", "International students", "", "None", "Iran", "", "", "https://en.shirazu.ac.ir"))
add(s("uni_20260724", "uni_020", "International Islamic University Malaysia Scholarship", "IIUM", "University", "All", "All", None, None, "Varies", "Varies", "https://www.iium.edu.my", "Scholarship for international students at IIUM", "International students", "", "None", "Malaysia", "", "", "https://www.iium.edu.my"))

# ============ DEMOGRAPHIC & IDENTITY (15) ============
add(s("demo_20260724", "demo_001", "The Gates Scholarship 2027-2028", "Gates Scholarship Program", "Demographic", "Undergraduate", "All", None, None, "Full cost of attendance", "Rolling", "https://www.college-financial-aid-advice.com/bill-gates-scholarships-for-minorities.html", "Highly selective scholarship for minority high school seniors eligible for Pell Grant", "Minority students, Pell eligible", "", "None", "US", "", "", "https://www.tgs.org"))
add(s("demo_20260724", "demo_002", "AICPA Scholarship for Minority Accounting Students", "AICPA", "Demographic", "Undergraduate", "Business", 1000, 10000, "$1,000 - $10,000", "Varies", "https://www.listsofscholarships.com/scholarships-for-minorities", "Scholarship for minority accounting students", "Minority students", "", "None", "US", "", "", ""))
add(s("demo_20260724", "demo_003", "LITA/LSSI Minority Scholarship Foundation", "LITA/LSSI", "Demographic", "Undergraduate", "All", None, None, "Varies", "Varies", "https://www.listsofscholarships.com/scholarships-for-minorities", "Scholarship for minority students in library/information science", "Minority students", "", "None", "US", "", "", ""))
add(s("demo_20260724", "demo_004", "American Indian Nurse Scholarship Award", "AINE", "Demographic", "Undergraduate", "Medicine", None, None, "Varies", "Varies", "https://www.listsofscholarships.com/scholarships-for-minorities", "Scholarship for American Indian/Alaska Native nursing students", "American Indian/Alaska Native", "", "None", "US", "", "", ""))
add(s("demo_20260724", "demo_005", "SME Education Foundation Scholarship", "SME", "Demographic", "Undergraduate", "Engineering", None, None, "$40,000", "Nov 1 - Feb 1", "https://www.listsofscholarships.com/scholarships-for-minorities", "Scholarship for minority students in engineering/technology", "Minority students", "", "None", "US", "", "", ""))
add(s("demo_20260724", "demo_006", "MSFN Muslim Scholarship Fund", "MSFN", "Demographic", "All", "All", None, None, "Varies", "Varies", "https://scholarshipset.com/scholarships-for/nigeria/undergraduate", "Scholarship for financially handicapped Muslim students in Nigeria", "Nigerian Muslim students", "", "None", "Nigeria", "", "", ""))
add(s("demo_20260724", "demo_007", "Generation Google Scholarship for Women in CS - Ireland", "Google", "Demographic", "Undergraduate", "Computer Science", None, None, "Varies", "Varies", "https://scholarshipbob.com/scholarships-for/ireland/undergraduate", "Scholarship for women in computer science in Ireland", "Women in CS", "", "None", "Ireland", "", "", ""))
add(s("demo_20260724", "demo_008", "Dell Technologies STEM Aspire Mentorship Program", "Dell Technologies", "Demographic", "Undergraduate", "STEM", None, None, "Varies", "Varies", "https://scholarshipbob.com/scholarships-for/ireland/undergraduate", "STEM mentorship scholarship program", "STEM students", "", "None", "International", "", "", ""))
add(s("demo_20260724", "demo_009", "MPOWER Financing Women in STEM Scholarship", "MPOWER Financing", "Demographic", "Undergraduate", "STEM", None, None, "Varies", "Jan 15, 2024", "https://www.scholarshipca.com/scholarships-by-course/stem", "Scholarship for female international/DACA students in STEM", "Female international/DACA students", "", "None", "US"))
add(s("demo_20260724", "demo_010", "Heck-Quaw American Indian Scholarship", "Heck-Quaw", "Demographic", "Undergraduate", "All", None, None, "Varies", "Varies", "https://www.listsofscholarships.com/scholarships-for-minorities", "Scholarship for Native American students", "Native American", "", "None", "US", "", "", ""))
add(s("demo_20260724", "demo_011", "Catharine Lealtad Scholarship", "Macalester College", "Demographic", "Undergraduate", "All", None, None, "Varies", "Varies", "https://www.listsofscholarships.com/scholarships-for-minorities", "Named for Macalester's first African American graduate, awarded to minority students", "African American students", "", "None", "US", "", "", ""))
add(s("demo_20260724", "demo_012", "BLM² Scholarship Foundation", "BLM² Foundation", "Demographic", "Undergraduate", "All", None, None, "Varies", "Varies", "https://www.listsofscholarships.com/scholarships-for-minorities", "Annual need-based scholarships for students of African American, Native American, Asian American, Pacific Islander, or Latino/Hispanic descent", "Minority students", "", "None", "US", "", "", ""))
add(s("demo_20260724", "demo_013", "Alexander Memorial Scholarship", "AINE", "Demographic", "Undergraduate", "Nursing", None, None, "Varies", "Varies", "https://www.listsofscholarships.com/scholarships-for-minorities", "Scholarship for students in nursing programs from minority backgrounds", "Minority nursing students", "", "None", "US", "", "", ""))
add(s("demo_20260724", "demo_014", "Lemons Ryhal Education Advancement Scholarship", "JCCIA", "Demographic", "Undergraduate", "All", None, None, "Varies", "Varies", "https://www.scholarships.com/financial-aid/college-scholarships/scholarships-by-state/illinois-scholarships", "Scholarship for Italian Americans or for minority/HBCU students", "Italian American or minority students", "", "None", "US", "", "", ""))
add(s("demo_20260724", "demo_015", "P.E.O. Scholar Award", "P.E.O. International", "Demographic", "Undergraduate", "All", None, None, "Varies", "Varies", "https://www.peointernational.org", "Scholarship for women pursuing higher education", "Women", "", "None", "International", "", "", "https://www.peointernational.org"))

# ============ FIELD OF STUDY (15) ============
add(s("field_20260724", "field_001", "STEM Scholarships at University of Bradford 2026", "University of Bradford", "University", "Graduate", "STEM", None, None, "Fully funded", "Varies", "https://www.ukscholarships.uk/scholarships-by-course/stem", "Five fully funded scholarships for women from specific countries in STEM", "Women in STEM", "UK", "None", "UK", "", "", ""))
add(s("field_20260724", "field_002", "Global STEM Leadership Masters Scholarship", "City St George's University", "University", "Graduate", "STEM", None, None, "Varies", "Varies", "https://www.ukscholarships.uk/scholarships-by-course/stem", "Leadership scholarship for STEM master's students", "STEM students", "", "None", "UK", "", "", ""))
add(s("field_20260724", "field_003", "University of Surrey Millett Award", "University of Surrey", "University", "Undergraduate", "STEM", None, None, "Varies", "Varies", "https://www.ukscholarships.uk/scholarships-by-course/stem", "Scholarship for STEM undergraduates on professional training year", "STEM undergraduates", "", "None", "UK", "", "", ""))
add(s("field_20260724", "field_004", "Engineering Scholarship for Nigerian Students 2026", "Various", "Platform", "Undergraduate", "Engineering", None, None, "Varies", "Varies", "https://scholarshipset.com/scholarships-for/nigeria/undergraduate", "Engineering scholarships for Nigerian students", "Engineering students", "", "None", "Nigeria", "", "", ""))
add(s("field_20260724", "field_005", "Angus Foundation Vocational Technical/Trade School Scholarship", "American Angus Association", "Organization", "High School", "Trade School", None, None, "$1,000", "May 1, 2026", "https://www.fastweb.com/college-scholarships/scholarships/193346-angus-foundation-vocational-technical-trade-school-scholarship", "Scholarship for high school seniors involved in Angus breed pursuing trade school", "High school seniors in FFA/4-H", "None", "None", "US", "", "", ""))
add(s("field_20260724", "field_006", "4Front Foundation Vocational Scholarship", "4Front Foundation", "Organization", "High School", "Trade School", None, None, "$2,500", "Varies", "https://migration.unigo.com/scholarships/by-type/vocational-and-career-college-scholarships", "Four $2,500 awards to Michigan residents pursuing apprenticeships or trade degrees", "Michigan residents 17+", "MI", "None", "US", "", "", ""))
add(s("field_20260724", "field_007", "Women in Skilled Trades Scholarship", "The Refrigeration School", "Organization", "Undergraduate", "Trade School", None, None, "Varies", "Varies", "https://migration.unigo.com/scholarships/by-type/vocational-and-career-college-scholarships", "Scholarship for female trade school students in HVAC/R", "Women in skilled trades", "", "None", "US", "", "", ""))
add(s("field_20260724", "field_008", "Pureland Supply Scholarship", "Pureland Supply", "Organization", "Undergraduate", "Trade School", None, None, "$500", "Varies", "https://migration.unigo.com/scholarships/by-type/vocational-and-career-college-scholarships", "Scholarship for students at accredited trade schools/community colleges", "Trade school students", "", "None", "US", "", "", ""))
add(s("field_20260724", "field_009", "CIRI Foundation Vocational Training Scholarships", "CIRI Foundation", "Organization", "Undergraduate", "Trade School", None, None, "$9,000", "Varies", "https://migration.unigo.com/scholarships/by-type/vocational-and-career-college-scholarships", "Vocational training scholarships for technical skill programs", "Vocational students", "", "None", "US", "", "", ""))
add(s("field_20260724", "field_010", "Soroptimist International Trade/Vocational Scholarship", "Soroptimist International", "Organization", "High School", "Trade School", None, None, "$2,500", "April 3, 2026", "https://lagrandesoroptimist.org/wp-content/uploads/2026/02/2026-TRADE_VOCATIONAL-SCHOOL-REV0126.pdf", "Scholarship for Union County HS seniors attending trade/vocational school", "HS seniors in Union County, NJ", "NJ", "None", "US", "", "", ""))
add(s("field_20260724", "field_011", "S-STEM Scholarship at Marion Technical College", "Marion Technical College", "University", "Undergraduate", "STEM", None, None, "Varies", "Varies", "https://www.mtc.edu/financial-aid/scholarships.html", "Scholarship for academically promising students in Science/Math/Technology with financial need", "Students with financial need", "", "None", "US", "", "", ""))
add(s("field_20260724", "field_012", "Shriners International Scholarship", "Shriners International", "Organization", "Undergraduate", "All", None, None, "Varies", "Varies", "https://www.shrinersinternational.org/", "Scholarship for students connected to Shriners fraternal organization", "Shriners members/families", "", "None", "US", "", "", ""))
add(s("field_20260724", "field_013", "Masonic Charities Arizona Scholarship", "Masonic Charities AZ", "Organization", "Undergraduate", "All", None, None, "Varies", "Varies", "https://www.masoniccharitiesaz.com/", "Scholarship for students connected to Arizona Masonic lodges", "Masonic connection", "", "None", "US", "", "", ""))
add(s("field_20260724", "field_014", "Hispanic Fund Scholarship 2026", "Hispanic Fund", "Organization", "Undergraduate", "All", None, None, "Varies", "Varies", "https://www.hispanicfund.org/scholarships", "Scholarship for Hispanic students pursuing higher education", "Hispanic students", "", "None", "US", "", "", "https://www.hispanicfund.org"))
add(s("field_20260724", "field_015", "NIGMS SEPA Science Education Partnership Award", "NIGMS/NIH", "Organization", "High School", "STEM", None, None, "Varies", "Varies", "https://grants.nih.gov", "Science education partnership award for high school students", "HS students in STEM", "", "None", "US", "", "", ""))

# ============ PLATFORM & AGGREGATOR (60) ============
add(s("plat_20260724", "plat_001", "Scholarships360 - Top Scholarships", "Scholarships360", "Platform", "All", "All", None, None, "Varies", "Rolling", "https://www.scholarships360.org", "Aggregator of top scholarships across all categories", "All students", "", "None", "International", "", "", "https://www.scholarships360.org"))
add(s("plat_20260724", "plat_002", "Bold.org Graduate Scholarships July 2026", "Bold.org", "Platform", "Graduate", "All", None, None, "Up to $10,000", "Rolling", "https://bold.org/scholarships/by-year/graduate-students-scholarships", "120+ graduate scholarships with approaching deadlines", "Graduate students", "", "None", "International", "", "", "https://bold.org"))
add(s("plat_20260724", "plat_003", "Fastweb - Best Graduate Scholarships 2026", "Fastweb", "Platform", "Graduate", "All", None, None, "Varies", "Rolling", "https://www.fastweb.com/college-search/articles/the-latest-and-greatest-for-grad-students", "Curated list of best graduate scholarships for 2026", "Graduate students", "", "None", "International", "", "", "https://www.fastweb.com"))
add(s("plat_20260724", "plat_004", "Marshall Scholarship 2026", "Marshall Scholarship Commission", "Platform", "Graduate", "All", None, None, "Fully funded", "Rolling", "https://www.marshallscholarship.org", "Prestigious scholarship for American students to study in the UK", "American graduates", "", "None", "UK", "", "", "https://www.marshallscholarship.org"))
add(s("plat_20260724", "plat_005", "Rutgers SHP Scholarships 2026", "Rutgers University", "Platform", "Graduate", "Health Professions", None, None, "Varies", "June 15, 2026", "https://shp.rutgers.edu/shp-scholarships", "General scholarship application for health professions graduate students", "Health professions students", "", "None", "US", "", "", "https://shp.rutgers.edu"))
add(s("plat_20260724", "plat_006", "Polk State College Foundation Scholarship 2026-2027", "Polk State College", "Platform", "All", "All", None, None, "Varies", "March 7, 2026", "https://foundation.polk.edu/application-deadline-extended-for-2026-2027-scholarships", "$1.2M in scholarships, application extended to March 7", "Polk State students", "FL", "None", "US", "", "", "https://foundation.polk.edu"))
add(s("plat_20260724", "plat_007", "Navarro College Foundation Scholarship", "Navarro College", "Platform", "All", "All", None, None, "Varies", "July 17, 2026", "https://www.facebook.com/NavarroCollege/posts/-good-news-theres-still-time-to-apply-for-navarro-college-foundation-scholarship/1479613280877928", "Foundation scholarship with extended deadline", "Navarro College students", "TX", "None", "US", "", "", "https://www.navarro.edu"))
add(s("plat_20260724", "plat_008", "Otero College 2026-2027 Scholarship Application", "Otero College", "Platform", "All", "All", None, None, "Varies", "April 15, 2026", "https://otero.edu/the-2026-2027-scholarship-application-is-now-open", "College-wide scholarship application for new and returning students", "Otero College students", "CO", "None", "US", "", "", "https://otero.edu"))
add(s("plat_20260724", "plat_009", "Buffalo U Scholarship Portal 2026", "University at Buffalo", "Platform", "All", "All", None, None, "Varies", "Rolling", "https://buffalo.academicworks.com", "Social work and music scholarships for graduate students", "UB students", "NY", "None", "US", "", "", "https://buffalo.academicworks.com"))
add(s("plat_20260724", "plat_010", "ASU Scholarship Universe 2026", "Arizona State University", "Platform", "Undergraduate", "All", None, None, "Up to full tuition", "Rolling", "https://tuition.asu.edu/financial-aid/scholarships", "Internal and external scholarship matching via Scholarship Universe", "ASU students", "AZ", "None", "US", "", "", "https://tuition.asu.edu"))
add(s("plat_20260724", "plat_011", "USC Town and Gown Scholarships 2026-2027", "Town and Gown of USC", "Platform", "All", "All", None, None, "$2,607,500 total", "Rolling", "https://townandgownofusc.org/students/scholarship-information", "224 merit-based scholarships for USC students", "USC students", "CA", "None", "US", "", "", "https://townandgownofusc.org"))
add(s("plat_20260724", "plat_012", "Kansas Hagan Scholarship", "Hagan Scholarship Foundation", "Platform", "Undergraduate", "All", None, None, "Varies", "Varies", "https://www.scholarships.com/financial-aid/college-scholarships/scholarships-by-state/kansas-scholarships", "Need-based merit scholarship for Kansas students", "Kansas students", "KS", "None", "US", "", "", "https://www.haganscholarship.org"))
add(s("plat_20260724", "plat_013", "Kansas Meisinger Sr. Memorial Scholarship", "Meisinger Foundation", "Platform", "High School", "All", None, None, "Varies", "Varies", "https://www.scholarships.com/financial-aid/college-scholarships/scholarships-by-state/kansas-scholarships", "Flight training scholarship for Kansas students", "Kansas HS seniors", "KS", "None", "US", "", "", ""))
add(s("plat_20260724", "plat_014", "New Hampshire VMSDEP", "VA/KDH", "Platform", "Undergraduate", "All", None, None, "$2,500", "Varies", "https://www.scholarships.com/financial-aid/college-scholarships/scholarships-by-type/veteran-scholarships", "Education benefits for children of NH service members", "NH residents, military children", "NH", "None", "US", "", "", "https://www.dva.state.nh.us"))
add(s("plat_20260724", "plat_015", "American Legion Legacy Scholarship", "American Legion", "Platform", "Undergraduate", "All", None, None, "Varies", "Varies", "https://usveteransmagazine.com/scholarships", "Scholarship for children of military who died on active duty after 9/11", "Military children", "", "None", "US", "", "", "https://www.legion.org"))
add(s("plat_20260724", "plat_016", "American Legion Auxiliary Department Scholarship", "American Legion Auxiliary", "Platform", "Undergraduate", "All", None, None, "Varies", "Varies", "https://usveteransmagazine.com/scholarships", "Scholarship for Auxiliary-sponsored students in Florida", "Florida residents, military children", "FL", "None", "US", "", "", "https://www.legion-aux.org"))
add(s("plat_20260724", "plat_017", "Brown Spouse Tuition Assistance Program (STAP)", "Air Force Aid Society", "Platform", "Undergraduate", "All", None, None, "Varies", "Varies", "https://usveteransmagazine.com/scholarships", "Tuition assistance for spouses of active-duty Air Force members overseas", "Air Force spouses", "", "None", "US", "", "", "https://www.afa.org"))
add(s("plat_20260724", "plat_018", "KDVA Impact Scholarship Program", "KDVA", "Platform", "Undergraduate", "All", None, None, "$2,500", "Varies", "https://www.scholarships.com/financial-aid/college-scholarships/scholarships-by-type/veteran-scholarships", "Scholarship for KDVA members and families", "KDVA members/families", "", "None", "US", "", "", ""))
add(s("plat_20260724", "plat_019", "Virginia Military Survivors and Dependents Education Program", "Commonwealth of Virginia", "Platform", "Undergraduate", "All", None, None, "Varies", "Varies", "https://www.scholarships.com/financial-aid/college-scholarships/scholarships-by-type/veteran-scholarships", "Education benefits for spouses/children of VA-rated disabled veterans", "Virginia residents, military families", "VA", "None", "US", "", "", ""))
add(s("plat_20260724", "plat_020", "Kennedy King Memorial Scholarship", "Various", "Platform", "Community College", "All", None, None, "Varies", "Varies", "https://www.scholarships.com", "Scholarship for community college students", "Community college students", "", "None", "International", "", "", ""))
add(s("plat_20260724", "plat_021", "Niche $25,000 No Essay Scholarship", "Niche", "Platform", "All", "All", None, None, "$25,000", "Rolling", "https://www.niche.com/scholarships", "No-essay scholarship open to all students", "All students", "", "None", "International", "", "", "https://www.niche.com/scholarships"))
add(s("plat_20260724", "plat_022", "Scholars4Dev Transnational Scholarships", "Scholars4Dev", "Platform", "All", "All", None, None, "Varies", "Rolling", "https://www.scholars4dev.com/scholarships/", "Development-focused scholarships for students from developing countries", "Students from developing countries", "", "None", "International", "", "", "https://www.scholars4dev.com"))
add(s("plat_20260724", "plat_023", "Malmö University Scholarship 2026", "Malmö University", "Platform", "All", "All", None, None, "Varies", "Varies", "https://www.malmöuniversity.se", "Scholarships for international students at Malmö University, Sweden", "International students", "", "None", "EU", "", "", "https://www.malmöuniversity.se"))
add(s("plat_20260724", "plat_024", "Uppsala University Scholarship 2026", "Uppsala University", "Platform", "All", "All", None, None, "Varies", "Varies", "https://www.uu.se", "Scholarships for international master's students in Sweden", "International students", "", "None", "EU", "", "", "https://www.uu.se"))

# Check for duplicate names already in DB
import sqlite3
conn = sqlite3.connect('/home/workspace/scholarsearch/data/processed/scholarships.db')
c = conn.cursor()
c.execute('SELECT LOWER(TRIM(scholarship_name)) FROM scholarships')
existing = set(r[0] for r in c.fetchall())
conn.close()

def is_dup(name):
    n = name.lower().strip()
    # Exact match
    if n in existing:
        return True
    # Check within +/- 20% edit distance (simple check)
    for ex in existing:
        # Very basic: if one contains the other or they share >70% of words
        words_n = set(n.split())
        words_ex = set(ex.split())
        if words_n and words_ex:
            overlap = len(words_n & words_ex) / max(len(words_n), len(words_ex))
            if overlap > 0.7 and abs(len(n) - len(ex)) < max(len(n), len(ex)) * 0.3:
                return True
    return False

new_records = [r for r in records if not is_dup(r["scholarship_name"])]
dup_count = len(records) - len(new_records)

# Limit to 200
final_records = new_records[:200]

with open(OUT, "w") as f:
    json.dump(final_records, f, indent=2)

print(f"Total candidates: {len(records)}")
print(f"Duplicates removed: {dup_count}")
print(f"New unique records written: {len(final_records)}")
print(f"Output file: {OUT}")
