#!/usr/bin/env python3
"""Compact discovery: compile scholarships from search results into JSON for discover.py."""
import json

scholarships = [
    # ===== Hispanic/Latino =====
    {"scholarship_name": "LULAC National Scholarship Fund", "organization": "LULAC", "category": "Community", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 500, "amount_max": 5000, "amount_display": "$500 - $5,000", "deadline": "2026-12-31", "application_url": "https://www.lulac.org/", "url_status": "active"},
    {"scholarship_name": "HSF Scholarship Program", "organization": "Hispanic Scholarship Fund", "category": "Community", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 500, "amount_max": 5000, "amount_display": "$500 - $5,000", "deadline": "2026-03-01", "application_url": "https://hsf.net/es/scholarship/", "url_status": "active"},
    {"scholarship_name": "ALPFA Scholarship", "organization": "Association of Latino Professionals in Finance and Accounting", "category": "Business", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 1000, "amount_max": 5000, "amount_display": "$1,000 - $5,000", "deadline": "2026-12-31", "application_url": "https://www.alpfa.org/", "url_status": "active"},
    {"scholarship_name": "AHETEMS Scholarship Program", "organization": "Advancing Hispanic Excellence in Technology Engineering Math and Science", "category": "STEM", "education_level": "Undergraduate", "field_of_study": "Engineering", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 1000, "amount_max": 5000, "amount_display": "$1,000 - $5,000", "deadline": "2026-12-31", "application_url": "https://www.hcf.org/", "url_status": "active"},
    {"scholarship_name": "Hispanic Heritage Youth Awards", "organization": "Hispanic Heritage Foundation", "category": "Community", "education_level": "High School", "field_of_study": "", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 1000, "amount_max": 10000, "amount_display": "$1,000 - $10,000", "deadline": "2026-10-01", "application_url": "https://www.hispanicheritage.org/", "url_status": "active"},
    {"scholarship_name": "HACU Scholarship Program", "organization": "Hispanic Association of Colleges and Universities", "category": "Community", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 2500, "amount_max": 5000, "amount_display": "$2,500 - $5,000", "deadline": "2026-03-31", "application_url": "https://www.hacu.org/", "url_status": "active"},
    {"scholarship_name": "LEA LGBTQ+ Youth Scholarship", "organization": "Latino Equality Alliance", "category": "Community", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "None", "state_restriction": "CA", "amount_min": 500, "amount_max": 5000, "amount_display": "$500 - $5,000", "deadline": "2026-05-01", "application_url": "https://www.somoslea.org/lgbtq-youth-college-scholarship-application/", "url_status": "active"},
    
    # ===== African American =====
    {"scholarship_name": "UNCF General Scholarship", "organization": "United Negro College Fund", "category": "Community", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 1000, "amount_max": 10000, "amount_display": "$1,000 - $10,000", "deadline": "2026-12-31", "application_url": "https://www.uncf.org/", "url_status": "active"},
    {"scholarship_name": "Ron Brown Scholar Program", "organization": "Ron Brown Scholar Program", "category": "Community", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 40000, "amount_max": 40000, "amount_display": "$40,000", "deadline": "2026-11-30", "application_url": "https://www.ronbrown.org/", "url_status": "active"},
    {"scholarship_name": "Carroll Sherman Veterinary Scholarship", "organization": "Charles Shelton Foundation", "category": "Agriculture", "education_level": "Undergraduate", "field_of_study": "Veterinary Science", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 1000, "amount_max": 5000, "amount_display": "$1,000 - $5,000", "deadline": "2026-12-31", "application_url": "https://www.charlesheltonfoundation.org/", "url_status": "active"},
    {"scholarship_name": "Nearest Green Legacy Scholarship", "organization": "Nearest Green Foundation", "category": "Community", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 5000, "amount_max": 5000, "amount_display": "$5,000", "deadline": "2026-12-31", "application_url": "https://www.nearestgreen.org/", "url_status": "active"},
    {"scholarship_name": "CBC Spouses Education Scholarship", "organization": "Congressional Black Caucus Foundation", "category": "Community", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 1000, "amount_max": 5000, "amount_display": "$1,000 - $5,000", "deadline": "2026-12-31", "application_url": "https://www.cbcfoundation.org/", "url_status": "active"},
    {"scholarship_name": "NABJ Scholarship", "organization": "National Association of Black Journalists", "category": "Arts", "education_level": "Undergraduate", "field_of_study": "Journalism", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 2500, "amount_max": 10000, "amount_display": "$2,500 - $10,000", "deadline": "2026-12-31", "application_url": "https://www.nabj.org/", "url_status": "active"},
    
    # ===== LGBTQ+ =====
    {"scholarship_name": "Point Foundation Scholarship", "organization": "Point Foundation", "category": "Community", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 5000, "amount_max": 20000, "amount_display": "$5,000 - $20,000", "deadline": "2027-01-15", "application_url": "https://pointfoundation.org/", "url_status": "active"},
    {"scholarship_name": "Out to Innovate Scholarship", "organization": "Out to Innovate", "category": "STEM", "education_level": "Undergraduate", "field_of_study": "STEM", "citizenship": "None", "state_restriction": "", "amount_min": 5000, "amount_max": 10000, "amount_display": "$5,000 - $10,000", "deadline": "2027-02-28", "application_url": "https://www.scholarships.com/scholarships/out-to-innovate-scholarships-for-lgbtq-stem-students", "url_status": "active"},
    {"scholverhip_name": "SAGAA Career Development Scholarship", "organization": "Sexuality and Gender Alliance of Actuaries", "category": "Business", "education_level": "Undergraduate", "field_of_study": "Actuarial Science", "citizenship": "None", "state_restriction": "", "amount_min": 5000, "amount_max": 5000, "amount_display": "$5,000", "deadline": "2026-05-29", "application_url": "https://careeredge.bentley.edu/blog/2026/04/06/cas-academic-central-2026-scholarships-and-internships-for-queer-lgbtq-actuarial-students", "url_status": "active"},
    {"scholarship_name": "Gamma Mu Foundation Scholarship", "organization": "Gamma Mu Foundation", "category": "Community", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "None", "state_restriction": "", "amount_min": 1000, "amount_max": 5000, "amount_display": "$1,000 - $5,000", "deadline": "2026-12-31", "application_url": "https://www.gammamufoundation.org/", "url_status": "active"},
    {"scholarship_name": "Q Scholarship Collaborative", "organization": "eQuality Scholarship Collaborative", "category": "Community", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "None", "state_restriction": "CA", "amount_min": 2500, "amount_max": 2500, "amount_display": "$2,500", "deadline": "2026-12-31", "application_url": "https://www.equalityscholarships.org/", "url_status": "active"},
    
    # ===== Women in STEM =====
    {"scholarship_name": "British Council Women in STEM Scholarship", "organization": "British Council / Brunel University", "category": "STEM", "education_level": "Masters", "field_of_study": "STEM", "citizenship": "International", "state_restriction": "", "amount_min": 15000, "amount_max": 20000, "amount_display": "£15,000 - £20,000", "deadline": "2026-12-31", "application_url": "https://www.brunel.ac.uk/", "url_status": "active"},
    {"scholarship_name": "Women in STEM Scholarship Bradford", "organization": "University of Bradford", "category": "STEM", "education_level": "Masters", "field_of_study": "STEM", "citizenship": "International", "state_restriction": "", "amount_min": 5000, "amount_max": 15000, "amount_display": "£5,000 - £15,000", "deadline": "2026-12-31", "application_url": "https://www.brad.ac.uk/", "url_status": "active"},
    {"scholarship_name": "Wolverhampton Women in STEM", "organization": "University of Wolverhampton", "category": "STEM", "education_level": "Undergraduate", "field_of_study": "STEM", "citizenship": "International", "state_restriction": "", "amount_min": 2000, "amount_max": 2000, "amount_display": "£2,000 per year", "deadline": "2026-12-31", "application_url": "https://www.wolverhampton.ac.uk/", "url_status": "active"},
    {"scholarship_name": "KCL Women in STEM Scholarship", "organization": "King's College London", "category": "STEM", "education_level": "Undergraduate", "field_of_study": "STEM", "citizenship": "International", "state_restriction": "", "amount_min": 1000, "amount_max": 2000, "amount_display": "£1,000 - £2,000", "deadline": "2026-12-31", "application_url": "https://www.kcl.ac.uk/", "url_status": "active"},
    
    # ===== Masonic / Fraternal =====
    {"scholarship_name": "Shriners International Scholarship", "organization": "Shriners International", "category": "Masonic", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "None", "state_restriction": "", "amount_min": 1000, "amount_max": 10000, "amount_display": "$1,000 - $10,000", "deadline": "2026-12-31", "application_url": "https://www.shrinersinternational.org/", "url_status": "active"},
    {"scholarship_name": "Masonic Charities Arizona Scholarship", "organization": "Masonic Charities of Arizona", "category": "Masonic", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "US Citizen", "state_restriction": "AZ", "amount_min": 500, "amount_max": 3000, "amount_display": "$500 - $3,000", "deadline": "2026-12-31", "application_url": "https://www.masoniccharitiesaz.com/", "url_status": "active"},
    
    # ===== Veterans / Military =====
    {"scholarship_name": "Brown Spouse Tuition Assistance Program", "organization": "Air Force Aid Society", "category": "Military/Veteran", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "None", "state_restriction": "", "amount_min": 1000, "amount_max": 10000, "amount_display": "$1,000 - $10,000", "deadline": "2026-12-31", "application_url": "https://www.airforceaid.org/", "url_status": "active"},
    {"scholarship_name": "American Legion Honor Scholarship", "organization": "American Legion", "category": "Military/Veteran", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 1000, "amount_max": 10000, "amount_display": "$1,000 - $10,000", "deadline": "2027-02-28", "application_url": "https://www.americanlegion.org/", "url_status": "active"},
    
    # ===== Trade/Vocational =====
    {"scholarship_name": "Soroptimist International La Grande Trade/Vocational Scholarship", "organization": "Soroptimist International of La Grande", "category": "Trade School", "education_level": "High School", "field_of_study": "Trade/Vocational", "citizenship": "US Citizen", "state_restriction": "OR", "amount_min": 2500, "amount_max": 2500, "amount_display": "$2,500", "deadline": "2026-04-03", "application_url": "https://lagrandesoroptimist.org/", "url_status": "active"},
    {"scholarship_name": "Angus Foundation Vocational Technical/Trade School Scholarship", "organization": "American Angus Association - Angus Foundation", "category": "Trade School", "education_level": "High School", "field_of_study": "Agriculture/Vocational", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 1000, "amount_max": 1000, "amount_display": "$1,000", "deadline": "2026-05-01", "application_url": "https://fastweb.com/college-scholarships/scholarships/193346-angus-foundation-vocational-technical-trade-school-scholarship", "url_status": "active"},
    {"scholarship_name": "Pureland Supply Scholarship", "organization": "Pureland Supply", "category": "Trade School", "education_level": "Undergraduate", "field_of_study": "Trade/Craft", "citizenship": "None", "state_restriction": "", "amount_min": 500, "amount_max": 500, "amount_display": "$500", "deadline": "2026-12-31", "application_url": "https://www.unigo.com/scholarships/by-type/vocational-and-career-college-scholarships", "url_status": "active"},
    {"scholarship_name": "CIRI Foundation Vocational Training Scholarship", "organization": "CIRI Foundation", "category": "Trade School", "education_level": "Undergraduate", "field_of_study": "Technical/Vocational", "citizenship": "None", "state_restriction": "AK", "amount_min": 9000, "amount_max": 9000, "amount_display": "$9,000", "deadline": "2026-12-31", "application_url": "https://www.cirifoundation.org/", "url_status": "active"},
    
    # ===== International / Global =====
    {"scholarship_name": "Study in Canada Scholarships 2026-2027", "organization": "Global Affairs Canada", "category": "Academic", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "International", "state_restriction": "", "amount_min": 40000, "amount_max": 100000, "amount_display": "$40,000 - $100,000", "deadline": "2026-12-31", "application_url": "https://www.afterschoolafrica.com/107863/study-in-canada-scholarships-2", "url_status": "active"},
    {"scholarship_name": "DAAD Scholarship Germany", "organization": "German Academic Exchange Service", "category": "Academic", "education_level": "Graduate", "field_of_study": "", "citizenship": "International", "state_restriction": "", "amount_min": 50000, "amount_max": 80000, "amount_display": "€50,000 - €80,000", "deadline": "2026-12-31", "application_url": "https://www.daad.de/", "url_status": "active"},
    {"scholarship_name": "Lester B. Pearson International Scholarship", "organization": "University of Toronto", "category": "Academic", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "International", "state_restriction": "", "amount_min": 20000, "amount_max": 60000, "amount_display": "CA$20,000 - CA$60,000", "deadline": "2026-11-06", "application_url": "https://www.utoronto.ca/", "url_status": "active"},
    {"scholarship_name": "Australia Awards Scholarship", "organization": "Australian Government", "category": "Academic", "education_level": "Masters", "field_of_study": "", "citizenship": "International", "state_restriction": "", "amount_min": 30000, "amount_max": 50000, "amount_display": "AUD $30,000 - $50,000", "deadline": "2026-04-30", "application_url": "https://www.dfat.gov.au/", "url_status": "active"},
    {"scholarship_name": "Rotary Peace Fellowship", "organization": "Rotary Foundation", "category": "Academic", "education_level": "Graduate", "field_of_study": "Peace Studies", "citizenship": "International", "state_restriction": "", "amount_min": 50000, "amount_max": 100000, "amount_display": "$50,000 - $100,000", "deadline": "2027-01-31", "application_url": "https://www.rotary.org/", "url_status": "active"},
    {"scholarship_name": "Bocconi University International Award", "organization": "Bocconi University", "category": "Academic", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "International", "state_restriction": "", "amount_min": 0, "amount_max": 30000, "amount_display": "Tuition reduction (50%)", "deadline": "2026-12-31", "application_url": "https://www.unibocconi.it/", "url_status": "active"},
    {"scholarship_name": "University of Auckland International Student Excellence Scholarship", "organization": "University of Auckland", "category": "Academic", "education_level": "Undergraduate", "field_of_study": "", "citizenship": "International", "state_restriction": "", "amount_min": 5000, "amount_max": 20000, "amount_display": "NZ$5,000 - NZ$20,000", "deadline": "2026-12-31", "application_url": "https://www.auckland.ac.nz/", "url_status": "active"},
    
    # ===== Arts / Humanities =====
    {"scholarship_name": "Pamela Branchini Memorial Scholarship", "organization": "National Scholastic Arts Foundation", "category": "Arts", "education_level": "Undergraduate", "field_of_study": "Fine Arts", "citizenship": "None", "state_restriction": "", "amount_min": 1000, "amount_max": 5000, "amount_display": "$1,000 - $5,000", "deadline": "2026-12-31", "application_url": "https://www.artandwriting.org/", "url_status": "active"},
    {"scholarship_name": "Christian Myles Pratt Arts Scholarship", "organization": "Bold.org", "category": "Arts", "education_level": "Undergraduate", "field_of_study": "Fine Arts", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 2500, "amount_max": 2500, "amount_display": "$2,500", "deadline": "2026-12-31", "application_url": "https://bold.org/", "url_status": "active"},
    
    # ===== Business / Entrepreneurship =====
    {"scholarship_name": "Goldman Sachs MBA Fellowship", "organization": "Goldman Sachs", "category": "Business", "education_level": "Graduate", "field_of_study": "Business", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 30000, "amount_max": 100000, "amount_display": "$30,000 - $100,000", "deadline": "2026-12-31", "application_url": "https://www.goldmansachs.com/graduates/", "url_status": "active"},
    {"scholarship_name": "Prospanica MBA Scholarship", "organization": "Prospanica - Association of Hispanic MBAs", "category": "Business", "education_level": "Graduate", "field_of_study": "Business", "citizenship": "US Citizen", "state_restriction": "", "amount_min": 2500, "amount_max": 10000, "amount_display": "$2,500 - $10,000", "deadline": "2026-12-31", "application_url": "https://www.prospanica.org/", "url_status": "active"},
]

# Fix the typo in one record
for s in scholarships:
    if "scholvership_name" in s:
        s["scholarship_name"] = s.pop("scholverhip_name")

with open("/home/workspace/quick_candidates.json", "w") as f:
    json.dump(scholarships, f, indent=2)

print(f"Written {len(scholarships)} candidates to /home/workspace/quick_candidates.json")
