import { describe, expect, test } from "bun:test";
import { execute, migrate, openDatabase } from "../src/server/db";
import { approveCampaign, createCampaign, enrollContacts } from "../src/server/campaigns/service";
import { isEligibleToSend, loadQueueEligibility } from "../src/server/campaigns/eligibility";

function fixture() { const db = openDatabase(); migrate(db); execute(db, "INSERT INTO organizations (id, name) VALUES (?, ?), (?, ?)", ["org-a", "A", "org-b", "B"]); execute(db, "INSERT INTO contacts (id, organization_id, email) VALUES (?, ?, ?), (?, ?, ?)", ["c1", "org-a", "a@example.com", "c2", "org-b", "b@example.com"]); execute(db, "INSERT INTO sending_accounts (id, organization_id, provider, email, daily_send_limit) VALUES (?, ?, ?, ?, ?)", ["a1", "org-a", "mock", "sender@example.com", 1]); return db; }
test("draft campaigns are rejected by eligibility", () => { const campaign = { status: "draft", approved_at: null }; expect(isEligibleToSend({ email: "a@example.com" }, campaign)).toEqual({ eligible: false, reason: "campaign_not_approved" }); });
test("approval records only the server actor and enrollment persists", () => { const db = fixture(); const campaign = createCampaign(db, "org-a", { name: "Intro", steps: [{ subject: "Hi", body: "Hello" }] }); expect(campaign.status).toBe("draft"); const approved = approveCampaign(db, campaign.id, "org-a"); expect(approved.status).toBe("approved"); expect(approved.approved_by).toBe("system:provisional"); expect(enrollContacts(db, campaign.id, "org-a", ["c1"])).toBe(1); expect(db.query("SELECT COUNT(*) AS count FROM audit_log").get()).toEqual({ count: 1 }); });
test("suppression and account limits reject sends", () => { const approved = { status: "approved", approved_at: "2026-08-19T00:00:00Z", daily_send_limit: 1, sends_today: 1 }; expect(isEligibleToSend({ email: "a@example.com", suppressed: true }, approved)).toEqual({ eligible: false, reason: "suppressed" }); expect(isEligibleToSend({ email: "a@example.com" }, approved)).toEqual({ eligible: false, reason: "account_limit_reached" }); });
test("queue eligibility loads authoritative tenant state", () => { const db = fixture(); const campaign = createCampaign(db, "org-a", { name: "Intro", sending_account_id: "a1", sending_window_start: "00:00", sending_window_end: "23:59" }); approveCampaign(db, campaign.id, "org-a"); expect(loadQueueEligibility(db, "org-a", campaign.id, "c1")).toEqual({ eligible: true }); execute(db, "INSERT INTO suppression_list (organization_id, email, reason) VALUES (?, ?, ?)", ["org-a", "A@EXAMPLE.COM", "manual"]); expect(loadQueueEligibility(db, "org-a", campaign.id, "c1")).toEqual({ eligible: false, reason: "suppressed" }); expect(loadQueueEligibility(db, "org-b", campaign.id, "c2")).toEqual({ eligible: false, reason: "campaign_not_approved" }); });
test("schedule values are validated", () => { expect(() => isEligibleToSend({ email: "a@example.com" }, { status: "approved", approved_at: "now", sending_window_start: "25:99", sending_window_end: "26:00" })).toThrow("Invalid sending window"); const db = fixture(); expect(() => createCampaign(db, "org-a", { name: "Bad", sending_window_start: "25:99", sending_window_end: "26:00" })).toThrow("Invalid sending window"); });
test("cross-tenant sending accounts are rejected", () => { const db = fixture(); execute(db, "INSERT INTO sending_accounts (id, organization_id, provider, email) VALUES (?, ?, ?, ?)", ["b1", "org-b", "mock", "b@example.com"]); expect(() => createCampaign(db, "org-a", { name: "Wrong", sending_account_id: "b1" })).toThrow("Sending account not found or inactive"); });
