CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS organizations (id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS organization_members (organization_id TEXT NOT NULL, user_id TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'member', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY (organization_id, user_id), FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS sending_accounts (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, provider TEXT NOT NULL, email TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', credential_ciphertext TEXT, daily_send_limit INTEGER NOT NULL DEFAULT 100, timezone TEXT NOT NULL DEFAULT 'UTC', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE (organization_id, id), FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS contacts (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, email TEXT NOT NULL, first_name TEXT, last_name TEXT, custom_fields JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE (organization_id, email), UNIQUE (organization_id, id), FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS campaigns (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', approved_at TIMESTAMPTZ, approved_by TEXT, sending_account_id TEXT, sending_window_start TIME, sending_window_end TIME, daily_send_limit INTEGER NOT NULL DEFAULT 100, timezone TEXT NOT NULL DEFAULT 'UTC', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE (organization_id, id), FOREIGN KEY (organization_id, sending_account_id) REFERENCES sending_accounts(organization_id, id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS campaign_steps (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, campaign_id TEXT NOT NULL, step_order INTEGER NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, delay_minutes INTEGER NOT NULL DEFAULT 0, UNIQUE (campaign_id, step_order), FOREIGN KEY (organization_id, campaign_id) REFERENCES campaigns(organization_id, id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS campaign_contacts (campaign_id TEXT NOT NULL, contact_id TEXT NOT NULL, organization_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY (campaign_id, contact_id), FOREIGN KEY (organization_id, campaign_id) REFERENCES campaigns(organization_id, id) ON DELETE CASCADE, FOREIGN KEY (organization_id, contact_id) REFERENCES contacts(organization_id, id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, campaign_id TEXT, contact_id TEXT, sending_account_id TEXT, provider_message_id TEXT, status TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, sent_at TIMESTAMPTZ, subject TEXT NOT NULL DEFAULT '', body TEXT NOT NULL DEFAULT '', attempt_count INTEGER NOT NULL DEFAULT 1, error_code TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE (organization_id, id), FOREIGN KEY (organization_id, campaign_id) REFERENCES campaigns(organization_id, id) ON DELETE RESTRICT, FOREIGN KEY (organization_id, contact_id) REFERENCES contacts(organization_id, id) ON DELETE RESTRICT, FOREIGN KEY (organization_id, sending_account_id) REFERENCES sending_accounts(organization_id, id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, message_id TEXT, contact_id TEXT, type TEXT NOT NULL, payload JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), FOREIGN KEY (organization_id, message_id) REFERENCES messages(organization_id, id) ON DELETE RESTRICT, FOREIGN KEY (organization_id, contact_id) REFERENCES contacts(organization_id, id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS suppression_list (organization_id TEXT NOT NULL, email TEXT NOT NULL, reason TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY (organization_id, email), FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS audit_log (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, user_id TEXT, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS auth_passwords (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, password_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS auth_sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, organization_id TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), FOREIGN KEY (organization_id, user_id) REFERENCES organization_members(organization_id, user_id) ON DELETE CASCADE);

CREATE INDEX IF NOT EXISTS idx_contacts_org ON contacts(organization_id); CREATE INDEX IF NOT EXISTS idx_campaigns_org ON campaigns(organization_id); CREATE INDEX IF NOT EXISTS idx_messages_queue ON messages(organization_id, status, created_at); CREATE INDEX IF NOT EXISTS idx_events_org_created ON events(organization_id, created_at DESC); CREATE INDEX IF NOT EXISTS idx_sessions_token ON auth_sessions(token_hash);
INSERT INTO schema_migrations(version) VALUES ('001_initial') ON CONFLICT DO NOTHING;
