#!/usr/bin/env bash
# Moltbook Daily Digest for jakbot
# Fetches interactions from the last 24 hours and outputs a digest
# Usage: bash moltbook-digest.sh [--html]
#   --html  Output HTML-formatted digest (for email)

set -euo pipefail

CONFIG_FILE="${HOME}/.config/moltbook/credentials.json"
API_BASE="https://www.moltbook.com/api/v1"
HTML_MODE="${1:-}"

# Load API key
API_KEY=$(jq -r .api_key "$CONFIG_FILE" 2>/dev/null)
if [[ -z "$API_KEY" || "$API_KEY" == "null" ]]; then
    echo "ERROR: Moltbook API key not found in $CONFIG_FILE"
    exit 1
fi

# Test API key
STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $API_KEY" "$API_BASE/agents/me")
if [[ "$STATUS" == "401" ]]; then
    echo "ERROR: Moltbook API key is invalid (401 Unauthorized). Key needs to be rotated."
    exit 1
fi

TODAY=$(date '+%B %d, %Y')

# Fetch home dashboard (includes activity on your posts)
HOME_DATA=$(curl -s -H "Authorization: Bearer $API_KEY" "$API_BASE/home")

# Fetch notifications
NOTIF_DATA=$(curl -s -H "Authorization: Bearer $API_KEY" "$API_BASE/notifications?limit=50")

# Fetch agent profile for stats
PROFILE_DATA=$(curl -s -H "Authorization: Bearer $API_KEY" "$API_BASE/agents/me")

# Extract stats
KARMA=$(echo "$PROFILE_DATA" | jq -r '.agent.karma // "N/A"')
UNREAD=$(echo "$HOME_DATA" | jq -r '.your_account.unread_notification_count // 0')

if [[ "$HTML_MODE" == "--html" ]]; then
    # HTML output for email
    cat <<HTML
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #333;">
<h2 style="color: #e01b24;">🦞 Moltbook Daily Digest for jakbot</h2>
<p style="color: #666;">$TODAY</p>

<div style="background: #f5f5f5; border-radius: 8px; padding: 12px; margin: 16px 0;">
<strong>📊 Account Stats:</strong> Karma: $KARMA | Unread Notifications: $UNREAD
</div>
HTML

    # Activity on your posts
    ACTIVITY_COUNT=$(echo "$HOME_DATA" | jq '.activity_on_your_posts | length')
    if [[ "$ACTIVITY_COUNT" -gt 0 ]]; then
        echo "<h3 style='color: #333;'>💬 Activity on Your Posts</h3>"
        echo "<ul style='list-style: none; padding: 0;'>"
        
        while IFS= read -r post; do
            POST_ID=$(echo "$post" | jq -r '.post_id')
            POST_TITLE=$(echo "$post" | jq -r '.post_title')
            NEW_COUNT=$(echo "$post" | jq -r '.new_notification_count')
            COMMENTERS=$(echo "$post" | jq -r '.latest_commenters | join(", ")')
            POST_URL="https://www.moltbook.com/post/$POST_ID"
            
            cat <<ITEM
<li style="background: #fff; border: 1px solid #e0e0e0; border-radius: 8px; padding: 16px; margin-bottom: 12px;">
  <strong><a href="$POST_URL" style="color: #e01b24; text-decoration: none;">$POST_TITLE</a></strong><br>
  <span style="color: #666; font-size: 14px;">
    💬 $NEW_COUNT new notification(s) · 👥 From: $COMMENTERS<br>
    🔗 <a href="$POST_URL" style="color: #4a9eff;">$POST_URL</a>
  </span>
</li>
ITEM
        done < <(echo "$HOME_DATA" | jq -c '.activity_on_your_posts[]')
        
        echo "</ul>"
    else
        echo "<p style='color: #666;'>💬 No activity on your posts in the last 24h.</p>"
    fi

    # Notifications
    NOTIF_ITEMS=$(echo "$NOTIF_DATA" | jq -c '.notifications[:15]? // empty')
    NOTIF_COUNT=$(echo "$NOTIF_DATA" | jq '.notifications | length // 0')
    
    if [[ "$NOTIF_COUNT" -gt 0 ]]; then
        echo "<h3 style='color: #333;'>🔔 Recent Notifications</h3>"
        echo "<ul style='list-style: none; padding: 0;'>"
        
        while IFS= read -r notif; do
            NOTIF_TYPE=$(echo "$notif" | jq -r '.type // "unknown"')
            NOTIF_TEXT=$(echo "$notif" | jq -r '.text // .message // "N/A"')
            NOTIF_POST_ID=$(echo "$notif" | jq -r '.post_id // empty')
            
            if [[ -n "$NOTIF_POST_ID" ]]; then
                NOTIF_URL="https://www.moltbook.com/post/$NOTIF_POST_ID"
                echo "<li style='padding: 8px 0; border-bottom: 1px solid #eee;'>• [$NOTIF_TYPE] $NOTIF_TEXT — <a href=\"$NOTIF_URL\" style=\"color: #4a9eff;\">View thread</a></li>"
            else
                echo "<li style='padding: 8px 0; border-bottom: 1px solid #eee;'>• [$NOTIF_TYPE] $NOTIF_TEXT</li>"
            fi
        done < <(echo "$NOTIF_DATA" | jq -c '.notifications[:15][]')
        
        echo "</ul>"
    else
        echo "<p style='color: #666;'>🔔 No new notifications.</p>"
    fi

    cat <<FOOTER
<hr style="border: none; border-top: 1px solid #e0e0e0; margin: 24px 0;">
<p style="color: #999; font-size: 12px;">
  <a href="https://www.moltbook.com/u/jakbot" style="color: #4a9eff;">View jakbot's profile</a> · 
  This digest was automatically generated by jakbot's daily automation.
</p>
</body>
</html>
FOOTER

else
    # Plain text output
    echo "🦞 Moltbook Daily Digest for jakbot"
    echo "📅 $TODAY"
    echo ""
    echo "📊 Account Stats: Karma: $KARMA | Unread Notifications: $UNREAD"
    echo ""

    ACTIVITY_COUNT=$(echo "$HOME_DATA" | jq '.activity_on_your_posts | length')
    if [[ "$ACTIVITY_COUNT" -gt 0 ]]; then
        echo "💬 Activity on Your Posts (last 24h):"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        while IFS= read -r post; do
            POST_ID=$(echo "$post" | jq -r '.post_id')
            POST_TITLE=$(echo "$post" | jq -r '.post_title')
            NEW_COUNT=$(echo "$post" | jq -r '.new_notification_count')
            COMMENTERS=$(echo "$post" | jq -r '.latest_commenters | join(", ")')
            echo ""
            echo "📌 $POST_TITLE"
            echo "   🔗 https://www.moltbook.com/post/$POST_ID"
            echo "   💬 $NEW_COUNT new notification(s) · 👥 From: $COMMENTERS"
        done < <(echo "$HOME_DATA" | jq -c '.activity_on_your_posts[]')
    else
        echo "💬 No activity on your posts in the last 24h."
    fi

    echo ""
    NOTIF_COUNT=$(echo "$NOTIF_DATA" | jq '.notifications | length // 0')
    if [[ "$NOTIF_COUNT" -gt 0 ]]; then
        echo "🔔 Recent Notifications:"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        while IFS= read -r notif; do
            NOTIF_TYPE=$(echo "$notif" | jq -r '.type // "unknown"')
            NOTIF_TEXT=$(echo "$notif" | jq -r '.text // .message // "N/A"')
            NOTIF_POST_ID=$(echo "$notif" | jq -r '.post_id // empty')
            echo "• [$NOTIF_TYPE] $NOTIF_TEXT"
            if [[ -n "$NOTIF_POST_ID" ]]; then
                echo "  🔗 https://www.moltbook.com/post/$NOTIF_POST_ID"
            fi
        done < <(echo "$NOTIF_DATA" | jq -c '.notifications[:15][]')
    else
        echo "🔔 No new notifications."
    fi

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "View your profile: https://www.moltbook.com/u/jakbot"
fi
