import { useMemo, useState } from "react";
import { Copy, Download, RotateCcw, Sparkles } from "lucide-react";

type Form = Record<string, string>;
const empty: Form = { name:"", age:"", country:"United States", currency:"USD", profession:"", income:"", expenses:"", assets:"", debts:"", emergency:"", hours:"", capital:"", skills:"", objective:"", target:"", deadline:"", dependents:"", risk:"Moderate", liquidity:"", constraints:"" };
const fields = [
  ["name","Name","text"],["age","Age","number"],["country","Country","text"],["currency","Currency","text"],["profession","Profession","text"],["income","Monthly income","text"],["expenses","Monthly expenses","text"],["assets","Current assets","text"],["debts","Debts","text"],["emergency","Emergency savings","text"],["hours","Time available per day","text"],["capital","Capital available for investment","text"],["skills","Current skills","textarea"],["objective","Financial objective","textarea"],["target","Target amount","text"],["deadline","Target date or timeline","text"],["dependents","Dependents or family obligations","text"],["risk","Risk tolerance","select"],["liquidity","Liquidity needs","textarea"],["constraints","Legal, ethical, health, or work constraints","textarea"]] as const;

const phaseText = [
  "Complete diagnosis: analyze the financial situation, income-generating capacity, assets and liabilities, risk profile, strengths, bottlenecks, enriching habits, impoverishing habits, and the 20% of actions likely to drive 80% of results.",
  "Wealth map: create plans for immediate income, increasing main income, extra income sources, asset building, recurring income, and wealth creation. Rank opportunities by ease, speed, investment required, profit potential, and scalability.",
  "Accumulation strategy: create stages for 10,000; 50,000; 100,000; 500,000; and 1,000,000 units of the user's currency. For every stage explain what to do, what to avoid, where to invest time, where to invest money, and what skills to develop.",
  "Money-making machine: generate 10 ideas using current skills, 10 using AI, 10 online, 10 digital-asset ideas, and 10 scalable ideas. Score every idea for profit potential, return time, difficulty, and scalability. Show assumptions and a cheap validation test.",
  "Implementation plan: create 30-day, 90-day, 1-year, and 3-year plans with specific revenue, profit, legacy, and investment goals.",
  "Fatal mistakes: list major financial mistakes, middle-class pitfalls, bad investments, invisible waste, and limiting money beliefs relevant to the user's context.",
  "Millionaire mindset: explain how wealthy people think about risk, opportunities, decisions, and wealth-building systems, while avoiding stereotypes and unsupported claims."
];

function buildPrompt(form: Form) {
  const profile = fields.map(([key,label]) => `${label}: ${form[key] || "[not provided]"}`).join("\n");
  return `You are my ethical, legal, sustainable wealth-planning strategist. Use my profile below. Treat this as educational planning, not regulated financial advice. Do not promise returns. Separate facts, assumptions, estimates, scenarios, experiments, and decisions. Flag when a qualified local tax, legal, insurance, or investment professional is needed.\n\nMY PROFILE\n${profile}\n\nSEVEN-PHASE WORKFLOW\n${phaseText.map((p,i)=>`${i+1}. ${p}`).join("\n\n")}\n\nOUTPUT\nReturn an executive summary, diagnosis, ranked wealth map, accumulation table, money-making matrix, implementation timelines, mistakes to avoid, mindset principles, assumptions and risks, downside scenarios, and a prioritized next-action checklist. Use concrete arithmetic where possible. End with the single highest-leverage action I can complete today.`;
}

export default function App() {
  const [form,setForm] = useState<Form>(empty); const [copied,setCopied] = useState(false);
  const prompt = useMemo(()=>buildPrompt(form),[form]);
  const update=(key:string,value:string)=>setForm({...form,[key]:value});
  const sample=()=>setForm({...empty,name:"Example founder",age:"42",profession:"Operations and IT leader",income:"$7,500/month",expenses:"$5,200/month",assets:"$85,000",debts:"$28,000",emergency:"$18,000",hours:"1.5",capital:"$12,000",skills:"Operations, systems, education, writing, automation",objective:"Build durable income and reach financial independence",target:"$1,000,000",deadline:"10 years",dependents:"Spouse and one dependent",risk:"Moderate",liquidity:"Keep six months of expenses liquid",constraints:"No illegal, deceptive, or unsustainable tactics"});
  const copy=async()=>{await navigator.clipboard.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),1800)};
  const download=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([prompt],{type:"text/markdown"}));a.download="millionaire-maker-prompt.md";a.click();URL.revokeObjectURL(a.href)};
  return <main><header><div className="eyebrow"><Sparkles size={15}/> PERSONAL WEALTH OPERATING SYSTEM</div><h1>Millionaire<br/><em>Maker.</em></h1><p className="lede">Turn your actual situation into a practical, ethical wealth-building brief.</p></header><section className="layout"><form className="card" onSubmit={e=>e.preventDefault()}><div className="section-head"><span>01 — YOUR PROFILE</span><button type="button" className="ghost" onClick={sample}>Load sample</button></div><div className="grid">{fields.map(([key,label,type])=><label key={key} className={type==="textarea"?"wide":""}>{label}{type==="textarea"?<textarea value={form[key]} onChange={e=>update(key,e.target.value)} placeholder="Add context..."/>:type==="select"?<select value={form[key]} onChange={e=>update(key,e.target.value)}><option>Conservative</option><option>Moderate</option><option>Aggressive</option></select>:<input type={type} value={form[key]} onChange={e=>update(key,e.target.value)} placeholder="Enter value"/>}</label>)}</div><div className="actions"><button type="button" className="secondary" onClick={()=>setForm(empty)}><RotateCcw size={16}/> Reset</button><button type="button" className="primary" onClick={copy}><Copy size={16}/> {copied?"Copied":"Copy prompt"}</button></div></form><aside className="card preview"><div className="section-head"><span>02 — GENERATED BRIEF</span><button type="button" className="icon" onClick={download} title="Download Markdown"><Download size={17}/></button></div><div className="notice">Educational planning tool. Validate tax, legal, insurance, and investment decisions with qualified professionals.</div><pre>{prompt}</pre></aside></section><footer>Seven phases. One honest starting point. <span>Local-first · No account · No API key</span></footer></main>
}
