#!/usr/bin/env python3
"""Scaffold a new strategy for robinhood-trading-bot's Strategy Lab.

Generates a runnable src/<slug>.py (9-EMA placeholder logic, clearly marked)
and prints the exact registration anchors for src/backtest_runner.py.
"""
import argparse
import re
import sys
from pathlib import Path

TEMPLATE = '''"""{description}

Scaffold generated by Skills/new-strategy. Placeholder entry logic is a
9-EMA cross with volume confirmation -- replace the marked block with the
real strategy, keep the interface methods intact.
"""

import pandas as pd


class {class_name}:
    def __init__(self, config, risk, journal):
        cfg = config.get("{slug}", {{}})
        self.config, self.risk, self.journal = config, risk, journal
        self.timezone = config.get("timezone", "America/New_York")
        self.ema_length = int(cfg.get("ema_length", 9))
        self.volume_multiplier = float(cfg.get("volume_multiplier", 1.2))
        self.rr_ratio = float(cfg.get("rr_ratio", 2.0))
        self.atr_length = int(cfg.get("atr_length", 14))
        self.atr_multiplier = float(cfg.get("atr_multiplier", 0.5))
        self.max_holding_bars = int(cfg.get("max_holding_bars", 30))
        self.session_start = pd.Timestamp(cfg.get("session_start", "09:35")).time()
        self.session_end = pd.Timestamp(cfg.get("session_end", "15:45")).time()
        self._active_trades, self._entry_counts = {{}}, {{}}

    def _ny(self, ts):
        ts = pd.Timestamp(ts)
        return (ts.tz_localize("UTC") if ts.tzinfo is None else ts).tz_convert(self.timezone)

    def _atr(self, bars):
        previous = bars.close.shift(1)
        true_range = pd.concat([bars.high - bars.low, (bars.high - previous).abs(), (bars.low - previous).abs()], axis=1).max(axis=1)
        return float(true_range.tail(self.atr_length).mean())

    def generate_signal(self, symbol, bars, context=None):
        minimum = max(self.ema_length + 2, self.atr_length + 2, 20)
        if len(bars) < minimum or symbol in self._active_trades:
            return None
        ts = self._ny(bars.index[-1])
        key = (symbol, ts.date())
        if not self.session_start <= ts.time() < self.session_end or self._entry_counts.get(key, 0) >= 1:
            return None
        window = bars.tail(max(30, self.ema_length + 10)).copy()
        if any(column not in window for column in ("open", "high", "low", "close", "volume")):
            return None
        bar, previous = window.iloc[-1], window.iloc[-2]
        close, high, low, volume = map(float, (bar.close, bar.high, bar.low, bar.volume))
        previous_close = float(previous.close)
        if close <= 0 or previous_close <= 0 or volume <= 0:
            return None

        # --- BEGIN PLACEHOLDER: replace with the real <slug> entry logic ---
        ema = window.close.ewm(span=self.ema_length, adjust=False).mean()
        if pd.isna(ema.iloc[-1]) or pd.isna(ema.iloc[-2]):
            return None
        current_ema, previous_ema = float(ema.iloc[-1]), float(ema.iloc[-2])
        average_volume = float(window.volume.iloc[:-1].tail(20).mean())
        if average_volume <= 0 or volume < average_volume * self.volume_multiplier:
            return None
        atr = self._atr(window)
        if atr <= 0:
            return None
        long_entry = close > current_ema and previous_close <= previous_ema
        short_entry = close < current_ema and previous_close >= previous_ema
        if long_entry:
            stop = close - self.atr_multiplier * atr
            target = close + self.rr_ratio * (close - stop)
            qty = self.risk.calculate_qty(close, stop)
            if qty > 0:
                return self._signal(symbol, "long", close, stop, target, qty, ts, "{slug} placeholder entry (long)")
        if short_entry:
            stop = close + self.atr_multiplier * atr
            target = close - self.rr_ratio * (stop - close)
            qty = self.risk.calculate_qty(close, stop, allow_fractional=False)
            if qty > 0:
                return self._signal(symbol, "short", close, stop, target, qty, ts, "{slug} placeholder entry (short)")
        # --- END PLACEHOLDER ---
        return None

    def _signal(self, symbol, direction, entry, stop, target, qty, ts, reason):
        return {{"symbol": symbol, "direction": direction, "entry": round(entry, 2), "stop": round(stop, 2), "target": round(target, 2), "qty": qty, "timestamp": ts.isoformat(), "reason": reason}}

    def on_trade_entered(self, symbol, signal):
        self._active_trades[symbol] = dict(signal, entry_bar_count=0)
        key = (symbol, pd.Timestamp(signal["timestamp"]).date())
        self._entry_counts[key] = self._entry_counts.get(key, 0) + 1

    def check_exit(self, symbol, bars, broker):
        trade = self._active_trades.get(symbol)
        if not trade:
            return None
        trade["entry_bar_count"] += 1
        bar, ts = bars.iloc[-1], self._ny(bars.index[-1])
        high, low, close = map(float, (bar.high, bar.low, bar.close))
        long = trade["direction"] == "long"
        if long:
            exit_price, reason = ((trade["stop"], "stop_loss") if low <= trade["stop"] else (trade["target"], "target_hit") if high >= trade["target"] else (None, None))
        else:
            exit_price, reason = ((trade["stop"], "stop_loss") if high >= trade["stop"] else (trade["target"], "target_hit") if low <= trade["target"] else (None, None))
        if exit_price is None and (trade["entry_bar_count"] >= self.max_holding_bars or ts.time() >= self.session_end):
            exit_price, reason = close, "session_close" if ts.time() >= self.session_end else "max_holding_bars"
        if exit_price is None:
            return None
        pnl = (exit_price - trade["entry"]) * trade["qty"] if long else (trade["entry"] - exit_price) * trade["qty"]
        result = {{"symbol": symbol, "direction": trade["direction"], "entry": trade["entry"], "exit_price": round(exit_price, 2), "qty": trade["qty"], "pnl": round(pnl, 2), "rr": self.rr_ratio, "reason": reason, "exit_time": ts.isoformat()}}
        self.risk.update_cash(pnl)
        if self.journal:
            self.journal.log_trade(result)
        del self._active_trades[symbol]
        return result
'''


def to_class_name(slug: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[^a-zA-Z0-9]+", slug) if part) + "Strategy"


def main() -> int:
    parser = argparse.ArgumentParser(description="Scaffold a new Strategy Lab strategy")
    parser.add_argument("--slug", required=True, help="snake_case strategy name (e.g. orb_fvg)")
    parser.add_argument("--description", default="<description>", help="one-line strategy summary for the docstring")
    parser.add_argument("--repo", default="/home/workspace/robinhood-trading-bot", help="path to the trading-bot repo")
    args = parser.parse_args()

    slug = args.slug.strip()
    if not re.fullmatch(r"[a-z][a-z0-9_]*", slug):
        print(f"invalid slug '{slug}' — use snake_case", file=sys.stderr)
        return 2
    repo = Path(args.repo)
    target = repo / "src" / f"{slug}.py"
    if target.exists():
        print(f"refusing to overwrite {target}", file=sys.stderr)
        return 1

    target.write_text(TEMPLATE.format(description=args.description, class_name=to_class_name(slug), slug=slug))
    print(f"wrote {target}")
    print(f"class: {to_class_name(slug)}")
    print()
    print("Register in src/backtest_runner.py (3 edits):")
    print(f"  1. import:   from src.{slug} import {to_class_name(slug)}")
    print(f"  2. STRATEGY_MAP:  \"{slug}\": {to_class_name(slug)},")
    print(f'  3. day-loop set (~line 271): add "{slug}" to {{"ha_scalp", ...}}')
    print()
    print(f"Optional config block for config.yaml:\n  {slug}:")
    print('    session_start: "09:35"\n    session_end: "15:45"\n    rr_ratio: 2.0')
    print()
    print("Smoke test:")
    print(f"  cd {repo} && python3 backtest.py --strategy {slug} \\")
    print("    --symbols SPY QQQ AAPL TSLA NVDA --start <start> --end <end>")
    return 0


if __name__ == "__main__":
    sys.exit(main())
